version: "3.9"
services:
  app:
    image: python:3.8-slim-buster
    container_name: openaibot
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y build-essential software-properties-common git && 
        rm -rf /var/lib/apt/lists/* &&
        pip3 install -r requirements.txt &&
        streamlit run main.py --server.port 6969"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    working_dir: /app
